#!/usr/bin/env bash
set -e

for platform in $DOCKER_CROSSPLATFORMS; do
	(
		export KEEPDEST=1
		export DEST="$DEST/$platform" # bundles/VERSION/cross/GOOS/GOARCH/docker-VERSION
		mkdir -p "$DEST"
		ABS_DEST="$(cd "$DEST" && pwd -P)"
		export GOOS=${platform%/*}
		export GOARCH=${platform##*/}

		if [ "$GOOS" != "solaris" ]; then
			# TODO. Solaris cannot be cross build because of CGO calls.
			# we just need a simple client
			export LDFLAGS_STATIC_DOCKER=""
			# remove the "daemon" build tag from platforms that aren't supported
			export BUILDFLAGS=( "${ORIG_BUILDFLAGS[@]/ daemon/}" )
			source "${MAKEDIR}/binary-client"
		fi
	)
done
